export const projects = [
    {
      title: 'Pinal sir',
      description: "he is very Good teacher",
        image: '/images/1.png',
        tags: ['Solidity', 'Express', 'React', 'Node','Tuffele',"Gipphify"],
      source: 'https://kryptoverse002.netlify.app',
      visit: 'https://kryptoverse002.netlify.app',
      id: 0,
    },
    {
      title: 'Cryptoverse',
      description:"This is just a simple website where you would get the know the real time price of top 100 Crypotcurrency and you can also get the description of the particular coin and along will all this you can also get the real time news of any crypto currency ,and not only that you can also fither the news accordinfg to your specific coinsnews ",
      image: '/images/2.png',
      tags: ['React', 'JavaScript','Bingnews Api','Coinranking API'],
      source: 'https://crypto-world-universe.netlify.app',
      visit: 'https://crypto-world-universe.netlify.app/',
      id: 1,
    },
    {
      title: 'Movie-Keeda ',
      description: "This Website is truely build on the React js and it is a website where you search for the popular movie where you would get the small description of the movie as well as the total global imdb ratings of the movie",
      image: '/images/3.1.png',
        tags: ['React', 'moviedb api'],
      source: 'https://movie-keeda.netlify.app',
      visit: 'https://movie-keeda.netlify.app',
      id: 3,
    },
    {
      title: 'Car-Washers ',
      description: "This was my internship project where we had given the app to study and we had to make the replica of that app , so i had made this website which was the replica of that app with some of additional features added by me!",
      image: '/images/7.png',
        tags: ['React', 'email.js','tailwent css','google-firebase'],
      source: 'https://car-washers.netlify.app/',
      visit: 'https://car-washers.netlify.app/',
      id: 2,
    },
    
    {
      title: 'Gericht Restaurent',
      description: "This is a Pure React Based ,website that show the simple restaurent showing speciality of restaurent and menus ",
      image: '/images/5.png',
      tags: ['React js'],
      source: 'https://restaurent-website-hrithik.netlify.app/',
      visit: 'https://restaurent-website-hrithik.netlify.app/',
      id: 4,
    },
    {
      title: 'Doc-Word-Counter',
      description: "This is just a website which counts the word world along with that ,it will convert the text into Upercase,lower case ,copy text and remove extra space",
      image: '/images/6.png',
      tags: ['React js'],
      source: 'https://doc-word-counter.netlify.app/',
      visit: 'https://doc-word-counter.netlify.app/',
      id: 5,
    },
    {
      title: 'Hrx-Store',
      description: "it is a simple ecommerce website where vyou can find the things ,which are quite interesting ,mainly it is focused on the gammers",
      image: '/images/8.png',
      tags: ['Next js ','Sanity.io','Stripe'],
      source: 'https://hrx-store.vercel.app/',
      visit: 'https://hrx-store.vercel.app/',
      id: 6,
    },
  ];
  
  